jobs: 
- name: kyei_go_build_job
  plan:
  - get: kyei_go_dockerfile
    trigger: true
  - put: kyei_go_build_image
    params: {build: kyei_go_dockerfile}
resources:
- name: kyei_go_dockerfile
  type: git
  source:
   uri:  https://github.com/sirdesmond/concourse-docker-test.git
   branch: master
   paths: [concourse-docker-test/Dockerfile]
- name: kyei_go_build_image
  type: docker-image
  source: 
   repository: sirdesmond/docker-go-test
   email: {{docker_mail}}
   username: {{docker_user}}
   password: {{docker_pass}}


